const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const out = path.resolve(__dirname,'../../docs/company-mail/independent-frontend-7a43654');
fs.mkdirSync(out,{recursive:true});
const results=[];
const tests=[];
const test=(name,fn)=>tests.push({name,fn});
const revision='9007199254740993', next='9007199254740999';
const dialog=p=>p.getByRole('dialog');
const save=p=>dialog(p).getByRole('button',{name:'Save',exact:true});
const refresh=p=>dialog(p).getByRole('button',{name:'Refresh version',exact:true});
const description=p=>dialog(p).getByPlaceholder('Profile description (optional)');
const writes=p=>p.evaluate(()=>window.review.calls.filter(c=>c.method==='PATCH'));
const setup=(p,fn,arg)=>p.evaluate(fn,arg);
async function open(p,name='Review A'){await p.getByRole('row').filter({hasText:name}).getByRole('button').click();await p.getByRole('menuitem',{name:'Edit',exact:true}).click();await dialog(p).waitFor();}
async function enabled(locator,value){await locator.page().waitForFunction(({selector,value})=>{const e=document.querySelector(selector);return !!e&&e.disabled===!value},{selector:'[role=dialog] [data-slot=dialog-footer] button:last-child',value});assert.equal(await locator.isEnabled(),value);}
async function count(p,n){await p.waitForFunction(n=>window.review.calls.filter(c=>c.method==='PATCH').length===n,n);}
async function conflict(p){await setup(p,()=>window.review.writeError=409);await save(p).click();await count(p,1);await enabled(save(p),false);}
async function reviewed(p){await refresh(p).click();await dialog(p).getByRole('checkbox').waitFor();assert.equal(await save(p).isEnabled(),false);await dialog(p).getByRole('checkbox').check();}
async function close(p){await dialog(p).locator('[data-slot=dialog-close]').click();await dialog(p).waitFor({state:'hidden'});}

test('description-only conflict preserves all remote revocations/quotas and raw NULL',async p=>{
 await open(p);await description(p).fill('local description');await conflict(p);
 await setup(p,()=>{Object.assign(window.review.profiles[0],{can_send:false,daily_send_quota:90,daily_receive_quota:91,max_mailboxes:92,max_domains:93,can_create_domains:false,can_create_routes:false,can_create_api_keys:false,revision:'9007199254740999'});window.review.writeError=0;});
 await refresh(p).click();const check=dialog(p).getByRole('checkbox');await check.waitFor();assert.equal(await check.isChecked(),false);assert.equal(await save(p).isEnabled(),false);assert.match(await dialog(p).locator('pre').innerText(),/"can_send": false/);await check.check();await enabled(save(p),true);await save(p).click();await count(p,2);
 assert.deepEqual((await writes(p))[1].body,{expected_revision:next,description:'local description'});
 const remote=await p.evaluate(()=>window.review.profiles[0]);assert.equal(remote.can_send,false);assert.equal(remote.max_domains,93);assert.equal(remote.allowed_zone_ids,null);
});
test('explicit false / zero / empty list survive conflict confirmation',async p=>{
 // Establish list via authoritative refresh then reopen to bind initial storage.
 await setup(p,()=>window.review.profiles[0].allowed_zone_ids=['50000000-0000-4000-8000-000000000011']);await open(p);await refresh(p).click();await dialog(p).getByRole('checkbox').waitFor();await close(p);await open(p);
 await dialog(p).getByRole('switch').nth(0).click();await dialog(p).locator('input[type=number]').nth(0).fill('0');await dialog(p).getByRole('button',{name:'Allow all domains'}).click();await conflict(p);
 await setup(p,()=>{window.review.profiles[0].revision='9007199254740999';window.review.writeError=0;});await reviewed(p);await enabled(save(p),true);await save(p).click();await count(p,2);
 assert.deepEqual((await writes(p))[1].body,{expected_revision:next,can_send:false,daily_send_quota:0,allowed_zone_ids:[]});
});
test('NULL profile zones remain omitted on ordinary description save; no override inherit field',async p=>{await open(p);await description(p).fill('only description');await save(p).click();await count(p,1);assert.deepEqual((await writes(p))[0].body,{expected_revision:revision,description:'only description'});assert.equal(await p.evaluate(()=>window.review.profiles[0].allowed_zone_ids),null);});
test('unchanged form cannot submit',async p=>{await open(p);assert.equal(await save(p).isEnabled(),false);assert.equal((await writes(p)).length,0);});
test('same-field remote conflict is visible and deliberate preserved edit wins only after confirmation',async p=>{await open(p);await description(p).fill('local edit');await conflict(p);await setup(p,()=>{Object.assign(window.review.profiles[0],{description:'remote edit',revision:'9007199254740999'});window.review.writeError=0;});await refresh(p).click();await dialog(p).getByRole('checkbox').waitFor();assert.match(await dialog(p).locator('pre').innerText(),/remote edit/);assert.equal(await description(p).inputValue(),'local edit');assert.equal(await save(p).isEnabled(),false);await dialog(p).getByRole('checkbox').check();await save(p).click();await count(p,2);assert.equal(await p.evaluate(()=>window.review.profiles[0].description),'local edit');});
test('explicit same-field choice of ORIGINAL quota after seeing remote change is transmitted',async p=>{await open(p);await description(p).fill('keep description');await dialog(p).locator('input[type=number]').nth(0).fill('15');await conflict(p);await setup(p,()=>{Object.assign(window.review.profiles[0],{daily_send_quota:20,revision:'9007199254740999'});window.review.writeError=0;});await reviewed(p);assert.match(await dialog(p).locator('pre').innerText(),/"daily_send_quota": 20/);await dialog(p).locator('input[type=number]').nth(0).fill('10');await save(p).click();await count(p,2);assert.equal((await writes(p))[1].body.daily_send_quota,10,'explicit post-review choice of 10 must not silently disappear');});
for(const status of [500,409])test(`refresh GET ${status} freezes draft and successful retry recovers`,async p=>{await open(p);await description(p).fill('surviving draft');await setup(p,status=>window.review.readError=status,status);await refresh(p).click();await dialog(p).getByRole('alert').waitFor();assert.equal(await save(p).isEnabled(),false);assert.equal(await description(p).inputValue(),'surviving draft');assert.equal((await writes(p)).length,0);await setup(p,()=>{window.review.readError=0;window.review.profiles[0].revision='9007199254740999';});await reviewed(p);await enabled(save(p),true);await save(p).click();await count(p,1);assert.equal((await writes(p))[0].body.expected_revision,next);});
for(const status of [401,403])for(const seam of ['read','write'])test(`${seam} ${status} locks current session and SAME account re-login recovers`,async p=>{await open(p);await description(p).fill('denied draft');await setup(p,({seam,status})=>{window.review[seam==='read'?'readError':'writeError']=status;},{seam,status});if(seam==='read')await refresh(p).click();else await save(p).click();await p.locator('[role=alert]').filter({hasText:'synthetic-'+status}).waitFor();assert.equal(await save(p).isEnabled(),false);assert.equal(await refresh(p).isEnabled(),false);const n=(await writes(p)).length;await close(p);await p.getByRole('row').filter({hasText:'Review A'}).getByRole('button').click();assert.equal(await p.getByRole('menuitem',{name:'Edit',exact:true}).getAttribute('aria-disabled'),'true');await p.keyboard.press('Escape');await setup(p,()=>{window.review.readError=0;window.review.writeError=0;window.review.logout();window.review.login('admin-a');});await p.getByText('Review A',{exact:true}).waitFor();await open(p);await description(p).fill('new login edit');await save(p).click();await count(p,n+1);});
test('cancel close/reopen discards edits and binds fresh baseline; A to B has no leaked intent',async p=>{await open(p);await description(p).fill('discard me');await close(p);await open(p,'Review B');assert.equal(await description(p).inputValue(),'original');assert.equal(await save(p).isEnabled(),false);await description(p).fill('B edit');await save(p).click();await count(p,1);assert.match((await writes(p))[0].path,/000000000012$/);await open(p);assert.equal(await description(p).inputValue(),'original');assert.equal((await writes(p)).length,1);});
for(const mode of ['account','tenant','relogin'])test(`delayed old refresh cannot contaminate new ${mode} draft`,async p=>{await open(p);await description(p).fill('old draft');await setup(p,()=>window.review.delayRead=true);await refresh(p).click();await p.waitForFunction(()=>window.review.pending.length>0);await setup(p,mode=>{window.review.delayRead=false;if(mode==='account')window.review.login('admin-b');else if(mode==='tenant'){const t='10000000-0000-4000-8000-000000000022';window.review.profiles.forEach(p=>p.tenant_id=t);window.review.login('admin-a',t);}else{window.review.logout();window.review.login('admin-a');}},mode);await dialog(p).waitFor({state:'hidden'});await open(p,'Review B');await description(p).fill('new draft');await setup(p,()=>window.review.release());assert.equal(await description(p).inputValue(),'new draft');assert.equal(await dialog(p).getByRole('checkbox').count(),0);await enabled(save(p),true);await save(p).click();await count(p,1);assert.match((await writes(p))[0].path,/000000000012$/);});
test('delayed old PATCH cannot close or unlock a new session PATCH',async p=>{await open(p);await description(p).fill('old write');await setup(p,()=>window.review.delayWrite=true);await save(p).click();await count(p,1);await setup(p,()=>window.review.login('admin-b'));await dialog(p).waitFor({state:'hidden'});await open(p,'Review B');await description(p).fill('new write');await save(p).click();await count(p,2);await setup(p,()=>window.review.pending.shift()());assert.equal(await dialog(p).isVisible(),true);assert.equal(await dialog(p).getByRole('button',{name:'Saving...'}).isEnabled(),false);await setup(p,()=>window.review.release());await dialog(p).waitFor({state:'hidden'});assert.equal((await writes(p)).length,2);});
test('repeated 409 never blindly replays and can recover after new refresh',async p=>{await open(p);await description(p).fill('retained');await conflict(p);await reviewed(p);await save(p).click();await count(p,2);await enabled(save(p),false);await setup(p,()=>{window.review.writeError=0;window.review.profiles[0].revision='9007199254740999';});await reviewed(p);await save(p).click();await count(p,3);});
test('SSE invalidation drops prior confirmation and requires fresh manual review',async p=>{await open(p);await description(p).fill('draft');await reviewed(p);await enabled(save(p),true);await setup(p,()=>window.review.invalidate());await dialog(p).getByRole('alert').waitFor();assert.equal(await save(p).isEnabled(),false);assert.equal(await dialog(p).getByRole('checkbox').count(),0);assert.equal((await writes(p)).length,0);await reviewed(p);await save(p).click();await count(p,1);});
test('missing target during refresh freezes; close and select valid B recovers',async p=>{await open(p);await description(p).fill('old A');await setup(p,()=>window.review.profiles.splice(0,1));await refresh(p).click();await dialog(p).getByRole('alert').waitFor();assert.equal(await save(p).isEnabled(),false);await close(p);await open(p,'Review B');await description(p).fill('valid B');await save(p).click();await count(p,1);assert.match((await writes(p))[0].path,/000000000012$/);});
test('unchecking confirmation and refreshing again remove write eligibility',async p=>{await open(p);await description(p).fill('draft');await reviewed(p);await enabled(save(p),true);await dialog(p).getByRole('checkbox').uncheck();await enabled(save(p),false);await dialog(p).getByRole('checkbox').check();await refresh(p).click();await p.waitForFunction(()=>document.querySelector('[role=dialog] section input[type=checkbox]')?.checked===false);assert.equal(await save(p).isEnabled(),false);assert.equal((await writes(p)).length,0);});
test('refresh 500 then page reload restores editing without frozen old draft',async p=>{await setup(p,()=>window.review.readError=500);await open(p);await refresh(p).click();await dialog(p).getByRole('alert').waitFor();await close(p);await p.reload();await p.getByText('Review A',{exact:true}).waitFor();await open(p);await description(p).fill('after reload');await save(p).click();await count(p,1);});
for(const kind of ['incomplete','foreign-tenant','system'])test(`refresh rejects ${kind} snapshot then recovers after valid authoritative read`,async p=>{await open(p);await description(p).fill('safe draft');await setup(p,kind=>{const p=window.review.profiles[0];if(kind==='incomplete')delete p.can_send;else if(kind==='foreign-tenant')p.tenant_id='10000000-0000-4000-8000-000000000022';else p.is_system=true;},kind);await refresh(p).click();await dialog(p).getByRole('alert').waitFor();assert.equal(await save(p).isEnabled(),false);assert.equal((await writes(p)).length,0);await setup(p,()=>window.review.profiles[0]=window.review.makeProfile());await reviewed(p);await save(p).click();await count(p,1);assert.deepEqual((await writes(p))[0].body,{expected_revision:revision,description:'safe draft'});});
(async()=>{const browser=await chromium.launch({executablePath:process.env.REVIEW_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox']});const version=browser.version();for(const {name,fn} of tests){const context=await browser.newContext();const p=await context.newPage();p.setDefaultTimeout(6000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());try{await p.goto('http://127.0.0.1:4179/review-independent/index.html');await p.getByText('Review A',{exact:true}).waitFor();await fn(p);assert.deepEqual(errors,[]);results.push({name,status:'passed'});}catch(e){const artifact=`failure-${results.length+1}.png`;await p.screenshot({path:path.join(out,artifact),fullPage:true});results.push({name,status:'failed',error:e.message,pageErrors:errors,requests:await p.evaluate(()=>window.review?.calls),artifact});}console.log(results.at(-1).status.toUpperCase(),name,results.at(-1).error||'');await context.close();}await browser.close();const report={scope:'real Chromium, candidate component on Vite; synthetic API and auth; real locale, Base UI, SWR, API/session/event transport. NOT shipping Next runtime, PG authz or durable acceptance.',candidate:'7a436549ace77d1baf30f33f6fb8e163077fe34c',baseline:'93005b644c1f39fa85072fe913156cf3d6c798e1',chromium:version,passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,results};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2)+'\n');process.exitCode=report.failed?1:0;})();
