import { configDefaults, defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    // Real protocol HTTP/PG fixtures are generated by the opt-in Go producer.
    // Keep this suite separate instead of skipping it when fixtures are absent.
    exclude: [...configDefaults.exclude, "components/company/r5-protocol-shared-components.test.tsx"],
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    css: false,
    restoreMocks: true,
    clearMocks: true,
  },
});
